---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: true

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true
  become: true
