---

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - openjdk-17-jdk
    - git
    - nginx

- name: Ensure .ssh directory exists
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'

- name: Copy SSH private key for GitHub access
  copy:
    src: id_rsa  # This file should be in roles/nginx_java_git/files/id_rsa
    dest: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Add GitHub to known_hosts
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    path: /home/ubuntu/.ssh/known_hosts

- name: Set permissions on known_hosts
  file:
    path: /home/ubuntu/.ssh/known_hosts
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Ensure /opt/springboot-app directory exists
  file:
    path: /opt/springboot-app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes

- name: Clone Spring Boot repo using SSH
  git:
    repo: 'git@github.com:thani2808/Dev-role-Springboot-proj.git'
    dest: /opt/springboot-app
    version: main
    key_file: /home/ubuntu/.ssh/id_rsa
    accept_hostkey: yes
  become: yes
  become_user: ubuntu

- name: Run Spring Boot app
  shell: nohup java -jar /opt/springboot-app/target/*.jar > /opt/app.log 2>&1 &
  args:
    chdir: /opt/springboot-app
    creates: /opt/app.log

- name: Configure Nginx reverse proxy
  copy:
    dest: /etc/nginx/sites-available/springboot
    content: |
      server {
          listen 80;
          server_name localhost;
          location / {
              proxy_pass http://localhost:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/springboot
    dest: /etc/nginx/sites-enabled/springboot
    state: link
    force: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted